language: ruby

rvm:
  - 2.1

env:
  global:
    - RAILS_ENV=test

parallel: 16

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qy libicu-dev cmake

before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/gitlab.yml.ci config/gitlab.yml
  - env force=true bundle exec rake gitlab:setup force=yes

script:
  - env force=true parallel_rspec
  - env force=true parallel_spinach
  - if [ "x$CI_PARALLEL_JOB_NUMBER" = 'x0' ] ; then env force=true bundle exec rake jasmine:ci ; else true ; fi
